### PR TITLE
Remove customise a node tutorial

### LINKED ISSUE #113: Take down old documentation on customisation ('customise a node').

### PR DESCRIPTION
**Pull request by barneydobson**
Remove the tutorial, fix a formatting issue. New recommendations on node customisation will be given by #111 

Fixes #113 

# Discussion
- I'm not going to remove the code of the examples in case it is potentially useful. I don't know if we want to add like an 'archived tutorials' folder that we can say 'these still work but are not best practice' in case people think there is something useful in them?

### CODE REVIEW

**Comment by barneydobson** [comment]
@dalonsoa any idea what's causing the tests to fail? this seems to be across multiple repos that this has started happening (and if I rerun old tests that were passing they now fail). I fixed it on another repo with below, but that's just chatgpt whatever, I don't actually know what is happening.
image

**Comment by dalonsoa** [comment]
Yep. `pre-commit` action is failing everywhere due to recent updates to ["something"](https://github.com/pre-commit/action/issues/210). Unclear what. The maintainer is pretty rude, so we are all pretty pissed. 

In any case, being this repo public, you don't need to use `pre-commit` action. Just delete that action altogether and I'll setup pre-commit.ci, as we did with SWMManywhere.

**Comment by dalonsoa** [comment]
I've just done it myself. It should all work, now, and run pre-commit via pre-commit.ci.

**Review by dalonsoa — COMMENTED** [review]
You have removed it from the TOC/list of how-tos, but have not actually removed the `customise_a_node.py` file. Is that correct?

**Comment by dalonsoa** [comment]
Sorry, I missed that part of the description. I'd personally ditch the file altogether. If it is not best practice, we should not even show how it is done. But up to you. 

If you do so, put them in an `archive` subfolder and, within, a README.md file explaining this.

**Review by dalonsoa — APPROVED** [review]

**Pull request merged**
