### PR TITLE
Simplify the build of the docs and implements automatic deployment

### PR DESCRIPTION
**Pull request by dalonsoa**
This PR simplifies the building of the docs, automatically creating the components library and downloading `pandoc` if required, and adds an automatic publication step whenever there is a new release.

### CODE REVIEW

**Review by barneydobson — APPROVED** [review]
Looks good - I had some trouble with the formatting of component library when I deployed - but this at least seems to look good in the github viewer

**Comment by dalonsoa** [comment]
Could you elaborate? Now is the time to fix any possible issues on this front.

**Comment by barneydobson** [comment]
Oops sorry I didn't see your message, and merged, and then reverted

**Comment by barneydobson** [comment]
It was a while ago - off the top of my head I can't remember, maybe the bullet point formatting seemed unreliable. Were you able to serve the documentation locally to make sure it was formatting properly?

**Comment by barneydobson** [comment]
I think if it was OK locally then that's fine

**Pull request merged**
